export const acord1 =
        {  
            id: 1,
            title: "Resonancia magnética",
            spanD: "Comer bien antes",
            phar: "Una buena comida ayuda a marcar las venas y así facilitar el proceso.",
            spanD2: "Beber agua de forma moderada",
            phar2: "Mantenerse hidratado ayuda a marcar las venas y asi facilitar el proceso. Pero no consumas demaciado porque no podras ir al baño una vez comience el estudio.",
            spanD3: "Cierra los ojos y relájate",
            phar3: "Piensa en las cosas que quieres hacer una vez termine la resonancia, canta o piensa en recuerdos agradable.",
            spanD4: "Una manta",
            phar4: "Al estar en medio de una resonancia debemos permanecer quietos y es normal sentir frío, por eso es recomendable llevar una manta o pedir al enfermero/a que nos proporcione una.",
            spanD5: "Ropa Cómoda",
            phar5: "Recuerda que no tienes que llevar metales encima: hebillas, pulseras, etc. Usar ropa ancha y medias siempre son una buena elección.",
        }
export const acord2 =
        {
            id: 2,
            title: "Fatiga",
            spanD: "La fatiga es un síntoma invisible",
            phar: "No siempre es fácil convivir con la fatiga, ya que este síntoma puede afectar de manera significativa el funcionamiento normal de las personas con EM en el ámbito doméstico o en el trabajo.",
            spanD2: "Algunas recomendaciones para poder llevar todo en órden",
            phar2: "",
            spanD3: "Planificar el día",
            phar3: "Programa y planifica actividades esenciales durante los momentos en los que se tiene más energía.",
            spanD4: "Ajusta a tu medida los quehaceres",
            phar4: "Eliminar tareas no prioritarias permite ahorrar energía para las cosas importantes.",
            spanD5: "Evitar cafeína y bebidas alcohólicas",
            phar5: "La cafeina puede impedir dormir y el alcohol puede provocar que no se descanse bien.",
            spanD6: "Hacer ejercicio",
            phar6: "Es un consejo que se repite mucho pero es necesario entender la importancia que tiene la actividad física en cuanto a la salud física y mental.",
            spanD7: "Relajación",
            phar7: "Otra vez, es algo que ya se ha dicho, pero es muy importante practicar ejercicios de relajación como el yoga, o ejercicios de respiración.",
            spanD8: "Pide ayuda",
            phar8: "Si se detectan síntomas depresivos, es importante contactar con profesionales.",
        }
